### ISSUE TITLE
KTH Dataset cannot be downloaded

### ISSUE THREAD

**Issue by huiyang865** [BarclayII/hart-pytorch#1]
Hi,

Thanks for sharing the code.
But downloading the KTH Dataset need the NYU ID. Do you have some other links for this dataset.

**Comment by BarclayII** [comment]
I moved the file to Dropbox.  Please have a try.

**Comment by huiyang865** [comment]
Ｉ have downloaded the file from the Ｄropbox. Ａfter unpacking the .gz file, Ｉ get the ptb.p file. Ｈow can Ｉ transfer this files to the .jpg images? 

Ｉn the readme of your object, Ｉ can see some words that “
Download KTH Dataset first from here and unpack it to the repo directory. You will have KTHBoundingBoxInfo.txt and a directory called frames in the same place as the source code files.”

Ｂut Ｉ cannot find the frames directory and KTHBoundingBoxInfo.txt while unpacking the .gz file.
Ｈow to process the ＫTＨ dataset? Ｔhanks for your helpness.

**Comment by BarclayII** [comment]
Oops.. I sent the wrong file.  Could you try the new link again?

**Comment by huiyang865** [comment]
Done, thx!
